"""Fail-closed permission gate for displaying market value and max purchase.

This module creates no valuation and no max price. It only decides whether the
already-computed economics have enough identity + sold evidence to be shown as
decision-grade monetary guidance.
"""
from __future__ import annotations


def _num(value, default=0.0):
    try:
        return float(value)
    except (TypeError, ValueError):
        return float(default)


def build_valuation_evidence_gate(
    *,
    comp_valuation_basis,
    sold_comparable_count,
    valuation_confidence_score,
    exact_identity_gate,
    premium_identity=False,
    premium_exact_sold_count=0,
) -> dict:
    basis = str(comp_valuation_basis or "none").casefold()
    sold_count = max(0, int(sold_comparable_count or 0))
    valuation_confidence = max(0.0, min(100.0, _num(valuation_confidence_score)))
    identity_gate = exact_identity_gate or {}
    supports_exact = bool(identity_gate.get("supports_exact_comp_search"))
    supports_dynamic = bool(identity_gate.get("supports_dynamic_max_bid"))
    identity_status = str(identity_gate.get("status") or "LÅST").upper()
    premium_exact = max(0, int(premium_exact_sold_count or 0))

    blockers = []
    strengths = []

    if basis != "sold":
        blockers.append("värderingen bygger inte på verifierade sålda jämförelseobjekt")
    else:
        strengths.append("värderingen bygger på verifierade sålda jämförelseobjekt")

    if sold_count < 2:
        blockers.append("minst två matchande verifierade sålda jämförelseobjekt krävs")
    else:
        strengths.append(f"{sold_count} matchande verifierade sålda jämförelseobjekt")

    if valuation_confidence < 60:
        blockers.append(f"värderingssäkerheten är för låg ({valuation_confidence:.0f}/100)")
    else:
        strengths.append(f"värderingssäkerhet {valuation_confidence:.0f}/100")

    if not supports_exact:
        blockers.append("kortidentiteten räcker inte för exakt comp-matchning")
    else:
        strengths.append(f"kortidentiteten är {identity_status.casefold()} för exact-comp-sökning")

    if premium_identity:
        if premium_exact < 2:
            blockers.append("premiumkort kräver minst två exakta premiumförsäljningar")
        else:
            strengths.append(f"{premium_exact} exakta premiumförsäljningar")

    market_value_safe = not blockers

    # Base max-purchase is still generated by the existing conservative pricing
    # model. This permission only controls whether it may be shown. Dynamic bid
    # tightening remains stricter and requires the existing dynamic identity gate.
    max_purchase_safe = market_value_safe
    dynamic_max_bid_safe = market_value_safe and supports_dynamic

    return {
        "market_value_safe": market_value_safe,
        "max_purchase_safe": max_purchase_safe,
        "dynamic_max_bid_safe": dynamic_max_bid_safe,
        "blockers": blockers,
        "strengths": strengths,
        "sold_comparable_count": sold_count,
        "valuation_confidence_score": round(valuation_confidence),
        "identity_status": identity_status,
        "note": (
            "Grinden skapar inga pengarvärden. Den avgör bara om befintlig värdering "
            "och befintligt maxpris får visas som beslutsstarkt underlag."
        ),
    }
